---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging 
summary: Avere familiarità con il addebito, il modello di consumo, i prezzi e le configurazioni delle licenze basate sulla capacità. 
---
= Scopri di più sulle licenze basate sulla capacità per Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dovresti conoscere l'addebito e l'utilizzo della capacità delle licenze basate sulla capacità



== Modelli di consumo

I pacchetti di licenza basati sulla capacità sono disponibili con i seguenti modelli di consumo:

* *BYOL*: Bring Your Own License (BYOL). Una licenza acquistata da NetApp, che può essere utilizzata per implementare Cloud Volumes ONTAP in qualsiasi cloud provider.
+

NOTE: NetApp ha limitato l'acquisto, l'estensione e il rinnovo delle licenze BYOL. Per ulteriori informazioni, fare riferimento a  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilità limitata delle licenze BYOL per Cloud Volumes ONTAP"^] .



ifdef::azure[]

endif::azure[]

* *PAYGO*: Un abbonamento pay-as-you-go (PAYGO) è un abbonamento orario dal mercato del tuo cloud provider.
* *Annuale*: Un contratto annuale dal mercato del tuo cloud provider.


Tenere presente quanto segue:

* Se acquisti una licenza da NetApp (BYOL), devi anche abbonarti all'offerta PAYGO dal marketplace del tuo provider cloud. NetApp ha limitato le licenze BYOL. Alla scadenza delle licenze BYOL, dovrai sostituirle con abbonamenti al marketplace cloud.
+
La tua licenza viene sempre addebitata per prima, ma ti verrà addebitato il costo della tariffa oraria sul mercato nei seguenti casi:

+
** Se si supera la capacità concessa in licenza
** Se il periodo di validità della licenza scade


* Se disponi di un contratto annuale da un marketplace, _tutti_ i sistemi Cloud Volumes ONTAP implementati vengono addebitati in base a tale contratto. Non puoi combinare un contratto di mercato annuale con BYOL.
* Nelle regioni cinesi sono supportati solo sistemi a singolo nodo con BYOL. Le distribuzioni nella regione cinese sono esenti dalle restrizioni di licenza BYOL.




== Cambiare i pacchetti

Dopo l'implementazione, è possibile modificare il pacchetto per un sistema Cloud Volumes ONTAP che utilizza licenze basate sulla capacità. Ad esempio, se hai implementato un sistema Cloud Volumes ONTAP con il pacchetto Essentials, puoi cambiarlo nel pacchetto Professional se le tue esigenze di business sono cambiate.

link:task-manage-capacity-licenses.html["Scopri come modificare i metodi di ricarica"].

Per informazioni sulla conversione delle licenze basate su nodi in licenze basate sulla capacità, vedere



== Prezzi e configurazioni supportate

Per i dettagli sui prezzi, vai a https://bluexp.netapp.com/pricing/["Sito Web di NetApp BlueXP"^] .

I pacchetti di licenza basati sulla capacità sono disponibili con Cloud Volumes ONTAP 9.7 e versioni successive.



=== VM di storage

* Non sono previsti costi di licenza aggiuntivi per le SVM (Data-Serving Storage VM), ma è previsto un costo di capacità minimo di 4 TIB per SVM di servizio dati.
* Le SVM per il disaster recovery vengono addebitate in base alla capacità fornita.




=== Coppie HA

Per le coppie ha, il costo viene addebitato solo per la capacità fornita su un nodo. I dati sottoposti a mirroring sincrono sul nodo partner non vengono addebitati.



=== Volumi FlexClone e FlexCache

* La capacità utilizzata dai volumi FlexClone non verrà addebitata.
* I volumi FlexCache di origine e di destinazione sono considerati dati primari e addebitati in base allo spazio fornito.




== Limite di capacità

Nel modello di licenza basato sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti e la capacità totale suddivisa in livelli può essere scalata fino al limite del bucket del provider cloud.  Sebbene la licenza non imponga restrizioni di capacità, seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering.

Per informazioni sui limiti di capacità di ciascun provider cloud, fare riferimento alla relativa documentazione:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentazione AWS"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentazione di Azure per i dischi gestiti"^]E https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentazione di Azure per l'archiviazione BLOB"^]
* https://cloud.google.com/storage/docs/buckets["Documentazione di Google Cloud"^]




== Numero massimo di sistemi

Con le licenze basate sulla capacità, il numero massimo di sistemi Cloud Volumes ONTAP è limitato a 24 per account BlueXP . Un _sistema_ è una coppia Cloud Volumes ONTAP ha, un sistema a nodo singolo Cloud Volumes ONTAP o qualsiasi altra VM storage creata. La VM di storage predefinita non viene contata rispetto al limite. Questo limite si applica a tutti i modelli di licenza.

Ad esempio, supponiamo di disporre di tre ambienti di lavoro:

* Un sistema Cloud Volumes ONTAP a nodo singolo con una VM di storage (si tratta della VM di storage predefinita creata durante l'implementazione di Cloud Volumes ONTAP)
+
Questo ambiente di lavoro conta come un unico sistema.

* Un sistema Cloud Volumes ONTAP a nodo singolo con due VM di storage (la VM di storage predefinita, più una VM di storage aggiuntiva creata dall'utente)
+
Questo ambiente di lavoro conta come due sistemi: Uno per il sistema a nodo singolo e uno per la VM di storage aggiuntiva.

* Una coppia Cloud Volumes ONTAP ha con tre VM storage (la VM storage predefinita, più due VM storage aggiuntive create)
+
Questo ambiente di lavoro conta tre sistemi: Uno per la coppia ha e due per le VM storage aggiuntive.



Si tratta di sei sistemi in totale. Avrai quindi spazio per altri 14 sistemi nel tuo account.

Se si dispone di un'implementazione di grandi dimensioni che richiede più di 24 sistemi, contattare il rappresentante dell'account o il team di vendita.

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["Scopri di più sugli account BlueXP"^].

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Scopri i limiti di archiviazione per AWS, Azure e Google Cloud"^].



== Note sulla ricarica

I seguenti dettagli consentono di comprendere il funzionamento della ricarica con le licenze basate sulla capacità.



=== Costo minimo

È previsto un costo minimo di 4 TIB per ciascuna VM di storage che fornisce dati e che dispone di almeno un volume primario (lettura/scrittura). Se la somma dei volumi primari è inferiore a 4 TIB, BlueXP applica la carica minima di 4 TIB a quella VM di storage.

Se non hai ancora effettuato il provisioning di volumi, il costo minimo non viene applicato.

Per il pacchetto Essentials, la tariffa per la capacità minima di 4 TiB non si applica alle VM di archiviazione che contengono solo volumi secondari (di protezione dei dati).  Ad esempio, se si dispone di una VM di archiviazione con 1 TiB di dati secondari, verrà addebitato solo quel 1 TiB di dati.  Con il tipo di pacchetto Professional, la capacità minima di ricarica di 4 TiB si applica indipendentemente dal tipo di volume.



=== Eccedendo

Se superi la capacità BYOL, ti verranno addebitati i costi aggiuntivi a tariffe orarie basate sul tuo abbonamento al marketplace. I costi aggiuntivi vengono addebitati alle tariffe del marketplace, con preferenza per l'utilizzo prioritario della capacità disponibile da altre licenze. Se la tua licenza BYOL scade, dovrai passare a un modello di licenza basato sulla capacità tramite i marketplace cloud.



=== Pacchetto Essentials

Con il pacchetto Essentials, l'addebito viene effettuato in base al tipo di implementazione (ha o nodo singolo) e al tipo di volume (primario o secondario). I prezzi da alto a basso sono nel seguente ordine: _Essentials Primary ha_, _Essentials Primary Single Node_, _Essentials Secondary ha_ e _Essentials Secondary Single Node_. In alternativa, quando acquisti un contratto di marketplace o accetti un'offerta privata, le spese in termini di capacità saranno identiche per qualsiasi tipo di implementazione o volume.

Il licensing si basa interamente sul tipo di volume creato all'interno dei sistemi Cloud Volumes ONTAP:

* Nodo singolo Essentials: Volumi in lettura/scrittura creati in un sistema Cloud Volumes ONTAP usando solo un nodo ONTAP.
* Essentials ha: Volumi in lettura/scrittura utilizzando due nodi ONTAP in grado di eseguire il failover l'uno sull'altro per un accesso ai dati senza interruzioni.
* Essentials Secondary Single Node: Volumi di tipo Data Protection (DP), generalmente volumi di destinazione SnapMirror o SnapVault di sola lettura, creati in un sistema Cloud Volumes ONTAP usando solo un nodo ONTAP.
+

NOTE: Se un volume di sola lettura/DP diventa un volume primario, BlueXP  lo considera come dati primari e i costi di addebito vengono calcolati in base al tempo in cui il volume si trovava in modalità di lettura/scrittura. Quando il volume viene nuovamente reso di sola lettura/DP, BlueXP  lo considera nuovamente come dati secondari e addebita di conseguenza utilizzando la migliore licenza corrispondente nel portafoglio digitale.

* Essentials ha secondaria: Volumi di tipo data Protection (DP) (di norma volumi di destinazione SnapMirror o SnapVault di sola lettura) creati in un sistema Cloud Volumes ONTAP utilizzando due nodi ONTAP in grado di eseguire il failover tra di loro per un accesso ai dati senza interruzioni.


.BYOL
Se hai acquistato una licenza Essentials da NetApp (BYOL) e superi la capacità concessa in licenza per quel tipo di implementazione e volume, il Digital Wallet di BlueXP addebiterà le spese eccessive rispetto a una licenza Essentials a prezzo più elevato (se disponibile). Questo accade perché utilizziamo prima la capacità disponibile che hai già acquistato come capacità prepagata prima di addebitare sul mercato. In assenza di capacità disponibile con la licenza BYOL, tale capacità superata verrà addebitata alle tariffe orarie on-demand del marketplace (PAYGO) e aggiungerà i costi alla fattura mensile.

Ecco un esempio. Supponiamo di disporre delle seguenti licenze per il pacchetto Essentials:

* Una licenza 500 TIB _Essentials Secondary ha_ con 500 TIB di capacità impegnata
* Una licenza 500 TIB _Essentials Single Node_ che ha solo 100 TIB di capacità impegnata


Un altro 50 TIB viene fornito su una coppia ha con volumi secondari. Invece di addebitare 50 TIB a PAYGO, il portafoglio digitale BlueXP addebita il 50 TIB in eccesso rispetto alla licenza _Essentials Single Node_. Tale licenza ha un prezzo superiore a _Essentials Secondary ha_, ma utilizza una licenza già acquistata e non aggiunge costi alla fattura mensile.

Nel portafoglio digitale BlueXP, il 50 TIB verrà indicato come addebitato rispetto alla licenza _Essentials Single Node_.

Ecco un altro esempio. Supponiamo di disporre delle seguenti licenze per il pacchetto Essentials:

* Una licenza 500 TIB _Essentials Secondary ha_ con 500 TIB di capacità impegnata
* Una licenza 500 TIB _Essentials Single Node_ che ha solo 100 TIB di capacità impegnata


Un altro TIB 100 viene sottoposto a provisioning su una coppia ha con volumi primari. La licenza acquistata non dispone di _Essentials Primary ha_ commit Capacity. Il prezzo della licenza _Essentials Primary ha_ è superiore a quello delle licenze _Essentials Primary Single Node_ e _Essentials Secondary ha_.

In questo esempio, il Digital Wallet di BlueXP addebita le spese eccessive alla tariffa di marketplace per i 100 TiB aggiuntivi. Le spese di eccedenza compariranno sulla vostra fattura mensile.

.Contratti di mercato o offerte private
Se hai acquistato una licenza Essentials come parte di un contratto di marketplace o di un'offerta privata, la logica BYOL non si applica e devi disporre dell'esatto tipo di licenza per l'utilizzo. Il tipo di licenza include il tipo di volume (primario o secondario) e il tipo di implementazione (ha o nodo singolo).

Ad esempio, supponiamo di distribuire un'istanza di Cloud Volumes ONTAP con la licenza Essentials. Esegui quindi il provisioning dei volumi in lettura-scrittura (nodo singolo primario) e di sola lettura (nodo singolo secondario). Il contratto del marketplace o l'offerta privata deve includere la capacità di _Essentials Single Node_ e _Essentials Secondary Single Node_ per coprire la capacità fornita. Tutte le capacità fornite che non fanno parte del contratto del marketplace o dell'offerta privata verranno addebitate alle tariffe orarie on-demand (PAYGO) e aggiungeranno i costi alla fattura mensile.
