---
sidebar: sidebar 
permalink: concept-azure-mktplace-direct.html 
keywords: azure marketplace direct, cvo in azure marketplace 
summary:  
---
= Scopri le opzioni di implementazione di Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp offre due opzioni per implementare Cloud Volumes ONTAP in Azure. Cloud Volumes ONTAP si affida tradizionalmente a BlueXP  per l'implementazione e l'orchestrazione. A partire da Cloud Volumes ONTAP 9.16.1, puoi sfruttare l'implementazione diretta di Azure Marketplace, un processo ottimizzato che fornisce l'accesso a un set limitato ma comunque potente di funzionalità e opzioni Cloud Volumes ONTAP.

Quando implementi Cloud Volumes ONTAP direttamente dal marketplace di Azure, non ti viene richiesto di configurare BlueXP  Connector o di soddisfare altri criteri di sicurezza e onboarding richiesti per la distribuzione di Cloud Volumes ONTAP tramite BlueXP . Dal marketplace di Azure, puoi implementare rapidamente Cloud Volumes ONTAP in pochi clic ed esplorarne le caratteristiche e le funzionalità principali nel tuo ambiente.

Una volta completata l'implementazione nel marketplace di Azure, è possibile rilevare questi sistemi in BlueXP . Dopo la Discovery, sarà possibile gestirli come ambienti di lavoro e sfruttare tutte le funzionalità di BlueXP . Fare riferimento alla link:task-deploy-cvo-azure-mktplc.html["Scopri i sistemi implementati in BlueXP "].

Di seguito viene riportato il confronto delle funzioni tra le due opzioni. Si noti che le funzionalità di un'istanza standalone implementata attraverso il marketplace di Azure cambiano quando viene rilevata in BlueXP .

[cols="3*"]
|===
|  | Marketplace Azure | BlueXP 


| *Onboarding* | Più breve e semplice, preparazione minima necessaria per l'implementazione diretta | Processo di inserimento più lungo, inclusa l'installazione del connettore BlueXP  


| *Tipi di macchine virtuali supportati*  a| 
Tipi di istanza EDS_v5 e LS_v3


NOTE: Il tipo di istanza L8s_v3 è supportato nel marketplace Azure per le configurazioni ha, ma non in BlueXP . BlueXP  non sarà in grado di rilevarlo correttamente durante il rilevamento.
| Gamma completa di tipi di VM. https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurazioni supportate in Azure"^] 


| *Licenza* | Licenza gratuita | Qualsiasi licenza basata sulla capacità. link:concept-licensing.html["Licenze Cloud Volumes ONTAP"] 


| *Supporto NetApp* | Non incluso | Disponibile, in base al tipo di licenza 


| *Capacità* | Fino a 500 GiB | Espandibile per configurazione 


| *Modello di distribuzione* | Implementazione in modalità ad alta disponibilità (ha) in una singola zona di disponibilità (AZ) | Tutte le configurazioni supportate, incluse le modalità ha e a nodo singolo, le implementazioni AZ singole e multiple 


| *Tipo di disco supportato* | SSD Premium, v2 dischi gestiti | Supporto più ampio. link:concept-storage.html#azure-storage["Configurazione predefinita per Cloud Volumes ONTAP"] 


| *Velocità di scrittura (modalità di scrittura veloce)* | Non supportato | Supportato, in base alla configurazione. link:concept-write-speed.html["Scopri le velocità di scrittura in Cloud Volumes ONTAP"]. 


| *Capacità di orchestrazione* | Non disponibile | Disponibile tramite BlueXP , in base al tipo di licenza 


| *Numero di VM di storage supportate* | Uno per implementazione | Macchine virtuali storage multiple in base alla tua configurazione. link:task-managing-svms-azure.html#supported-number-of-storage-vms["Numero di VM storage supportate"] 


| *Modifica del tipo di istanza* | Non supportato | Supportato 


| *Tiering FabricPool* | Non supportato | Supportato 
|===
.Link correlati
* Implementazione diretta del marketplace Azure: link:task-deploy-cvo-azure-mktplc.html["Implementa Cloud Volumes ONTAP dal marketplace di Azure"]
* Distribuzione BlueXP : link:task-getting-started-azure.html["Avvio rapido di Cloud Volumes ONTAP in Azure"]
* https://docs.netapp.com/us-en/bluexp-family/index.html["Documentazione BlueXP"^]

