---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Per Cloud Volumes ONTAP sono disponibili diverse opzioni di licenza. Ciascuna opzione consente di scegliere una configurazione che soddisfi le proprie esigenze. 
---
= Licenze Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per Cloud Volumes ONTAP sono disponibili diverse opzioni di licenza. Ciascuna opzione consente di scegliere un modello di consumo che soddisfi le proprie esigenze.



== Panoramica sulle licenze

Per i nuovi clienti sono disponibili le seguenti opzioni di licenza.

Licenze basate sulla capacità:: Paga più sistemi Cloud Volumes ONTAP nel tuo account NetApp in base alla capacità fornita. Include la possibilità di acquistare servizi dati cloud aggiuntivi.
Iscrizione Keystone:: Un servizio pay-as-you-grow e basato su abbonamento che offre un'esperienza di cloud ibrido perfetta per coppie ha (High Availability).


Le sezioni seguenti forniscono ulteriori dettagli su ciascuna di queste opzioni.


NOTE: Il supporto non è disponibile per l'uso di funzioni con licenza senza licenza.



== Licenze basate sulla capacità

I pacchetti di licenza basati sulla capacità consentono di pagare Cloud Volumes ONTAP per TIB di capacità. La licenza è associata al tuo account NetApp e ti consente di addebitare la licenza a più sistemi, purché sia disponibile una capacità sufficiente attraverso la licenza.

Ad esempio, è possibile acquistare una singola licenza 20 TIB, implementare quattro sistemi Cloud Volumes ONTAP e quindi allocare un volume 5 TIB per ciascun sistema, per un totale di 20 TIB. La capacità è disponibile per i volumi su ciascun sistema Cloud Volumes ONTAP implementato in quell'account.

Le licenze basate sulla capacità sono disponibili sotto forma di _pacchetto_. Quando si implementa un sistema Cloud Volumes ONTAP, è possibile scegliere tra diversi pacchetti di licenza in base alle esigenze aziendali.


NOTE: Mentre l'utilizzo e la misurazione effettivi per i prodotti e i servizi gestiti in BlueXP sono sempre calcolati in GiB e TiB, i termini GB/GiB e TB/TiB vengono utilizzati in modo intercambiabile. Ciò si riflette negli elenchi di Cloud Marketplace, nelle quotazioni, nelle descrizioni degli elenchi e in altra documentazione di supporto.



=== Pacchetti

I seguenti pacchetti basati sulla capacità sono disponibili per Cloud Volumes ONTAP.

Per un elenco dei tipi di VM supportati con i seguenti pacchetti basati sulla capacità, fare riferimento a:

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configurazioni supportate in Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurazioni supportate in Google Cloud"^]


endif::gcp[]



==== Freemium

Fornisce tutte le funzionalità Cloud Volumes ONTAP gratuitamente da NetApp (sono ancora applicati i costi per i cloud provider).

* Non sono necessari contratti o licenze.
* Il supporto di NetApp non è incluso.
* La capacità di provisioning per sistema Cloud Volumes ONTAP è limitata a 500 GiB.
* Puoi utilizzare fino a 10 sistemi Cloud Volumes ONTAP con l'offerta Freemium per account NetApp, in qualsiasi cloud provider.
* Se la capacità fornita per un sistema Cloud Volumes ONTAP supera i 500 GiB, BlueXP converte il sistema nel pacchetto Essentials.
+
Non appena un sistema viene convertito nel pacchetto Essentials, il <<Note sulla ricarica,costo minimo>> valido.

+
Tutti gli altri sistemi con meno di 500 GiB di capacità fornita rimangono su Freemium (purché siano stati implementati utilizzando l'offerta Freemium).





==== Elementi essenziali

Puoi pagare in base alla capacità in diverse configurazioni:

* Scegli la tua configurazione Cloud Volumes ONTAP:
+
** Un singolo nodo o sistema ha
** Storage a blocchi e file o dati secondari per disaster recovery (DR)


* Aggiungi qualsiasi servizio dati cloud di NetApp a un costo aggiuntivo


Per ulteriori informazioni, vedere link:concept-licensing-charging.html["Ulteriori informazioni sulle licenze basate sulla capacità"].



==== Ottimizzato

Pagare separatamente la capacità e le operazioni di i/o fornite.

* Nodo singolo Cloud Volumes ONTAP o ha
* La ricarica si basa su due componenti di costo: Storage e utilizzo (i/o).
+
Non verranno addebitati costi per i/o relativi alla replica dei dati (SnapMirror), ai backup (SnapVault) o ad NDMP.



ifdef::azure[]

* Disponibile in Azure Marketplace come offerta pay-as-you-go o come contratto annuale


endif::azure[]

ifdef::gcp[]

* Disponibile in Google Cloud Marketplace come offerta pay-as-you-go o come contratto annuale


endif::gcp[]

* Aggiungi qualsiasi servizio dati cloud di NetApp a un costo aggiuntivo




==== Professionale

Paga in base alla capacità per qualsiasi tipo di configurazione Cloud Volumes ONTAP con backup illimitati.

* Fornisce licenze per qualsiasi configurazione Cloud Volumes ONTAP
+
Nodo singolo o ha con carica della capacità per volumi primari e secondari alla stessa velocità

* Include backup di volumi illimitati utilizzando il backup e il ripristino BlueXP, ma solo per i sistemi Cloud Volumes ONTAP che utilizzano il pacchetto Professional.
+

NOTE: Per il backup e il ripristino di BlueXP  è richiesto un abbonamento PAY-as-you-go (PAYGO), tuttavia non sono previsti costi per l'utilizzo di questo servizio. Per ulteriori informazioni sull'impostazione delle licenze per il backup e il ripristino di BlueXP , consultare https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Impostare le licenze per il backup e ripristino BlueXP"^] .

* Aggiungi qualsiasi servizio dati cloud di NetApp a un costo aggiuntivo




=== Disponibilità di licenze basate sulla capacità

La disponibilità delle licenze PAYGO e BYOL per i sistemi Cloud Volumes ONTAP richiede che BlueXP  Connector sia attivo e funzionante. Per ulteriori informazioni, fare riferimento a https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["Scopri di più sui connettori"^].



=== Come iniziare

Scopri come iniziare a utilizzare le licenze basate sulla capacità:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Impostare la licenza per Cloud Volumes ONTAP in AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Impostare la licenza per Cloud Volumes ONTAP in Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Impostare la licenza per Cloud Volumes ONTAP in Google Cloud"]


endif::gcp[]



== Iscrizione Keystone

Un servizio pay-as-you-grow basato su abbonamento che offre un'esperienza di cloud ibrido perfetta per coloro che preferiscono i modelli di consumo OpEx per la gestione anticipata di CapEx o il leasing.

La ricarica si basa sulle dimensioni della capacità impegnata per una o più coppie Cloud Volumes ONTAP ha nel tuo abbonamento Keystone.

La capacità fornita per ciascun volume viene aggregata e confrontata periodicamente con la capacità impegnata del tuo abbonamento Keystone e gli eventuali superamenti vengono addebitati come burst sul tuo abbonamento Keystone.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Scopri di più su NetApp Keystone"^].



=== Configurazioni supportate

Gli abbonamenti Keystone sono supportati con le coppie ha. Al momento, questa opzione di licenza non è supportata dai sistemi a nodo singolo.



=== Limite di capacità

Ogni singolo sistema Cloud Volumes ONTAP supporta fino a 2 PIB di capacità attraverso dischi e tiering per lo storage a oggetti.



=== Come iniziare

Scopri come iniziare con un abbonamento Keystone:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Impostare la licenza per Cloud Volumes ONTAP in AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Impostare la licenza per Cloud Volumes ONTAP in Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Impostare la licenza per Cloud Volumes ONTAP in Google Cloud"]


endif::gcp[]



== Licenze basate su nodo

La licenza basata su nodo è il modello di licenza di generazione precedente che consente di concedere in licenza Cloud Volumes ONTAP per nodo. Questo modello di licenza non è disponibile per i nuovi clienti. La carica per nodo è stata sostituita con i metodi di carica per capacità descritti in precedenza.

NetApp ha pianificato la fine della disponibilità (EOA) e il supporto (EOS) delle licenze basate su nodi. Dopo la fine dell'EOS e la fine dell'anno, le licenze basate su nodi dovranno essere convertite in licenze basate sulla capacità.

Per informazioni, fare riferimento alla https://mysupport.netapp.com/info/communications/CPC-00589.html["Comunicazione con i clienti: CPC-00589"^].



=== Fine della disponibilità delle licenze basate su nodi

A partire dal 11 novembre 2024, la disponibilità limitata delle licenze basate su nodi è stata interrotta. Il supporto per le licenze basate su nodi termina il 31 dicembre 2024.

Se si dispone di un contratto valido basato su nodi che si estende oltre la data di fine disponibilità, è possibile continuare a utilizzare la licenza fino alla scadenza del contratto. Una volta scaduto il contratto, sarà necessario passare al modello di licenza basato sulla capacità. Se non si dispone di un contratto a lungo termine per un nodo Cloud Volumes ONTAP, è importante pianificare la conversione prima della data EOS.

Questa tabella fornisce ulteriori informazioni su ciascun tipo di licenza e sull'impatto della fine disponibilità sul reparto IT:

[cols="2*"]
|===
| Tipo di licenza | Impatto dopo la fine del ciclo di vita 


 a| 
Licenza valida basata su nodi acquistata tramite Bring Your Own License (BYOL)
 a| 
La licenza rimane valida fino alla scadenza. È possibile utilizzare le licenze non utilizzate esistenti basate su nodi per implementare nuovi sistemi Cloud Volumes ONTAP.



 a| 
Licenza scaduta basata su nodi acquistata tramite BYOL
 a| 
Non si avrà diritto a distribuire nuovi sistemi Cloud Volumes ONTAP utilizzando questa licenza. I sistemi esistenti potrebbero continuare a funzionare, ma non si riceverà alcun supporto o aggiornamento per i sistemi dopo la data EOS.



 a| 
Licenza valida basata su nodi con iscrizione PAYGO
 a| 
Cesserà di ricevere il supporto NetApp dopo la data di EOS, fino a quando l'utente non effettuerà la transizione a una licenza basata sulla capacità.

|===
.Esclusioni
NetApp riconosce che determinate situazioni richiedono particolare attenzione e la fine a ed EOS delle licenze basate su nodi non si applicano ai seguenti casi:

* Clienti USA del settore pubblico
* Implementazioni in modalità privata
* Implementazioni nella regione cinese di Cloud Volumes ONTAP in AWS


Per questi scenari particolari, NetApp offrirà supporto per soddisfare i requisiti di licenza esclusivi in conformità agli obblighi contrattuali e alle esigenze operative.


NOTE: Anche in questi scenari, i rinnovi di licenze e le nuove licenze basate su nodi sono validi per un massimo di un anno dalla data di approvazione.



== Conversione della licenza

BlueXP  permette una conversione perfetta delle licenze basate su nodi in base alla capacità grazie al tool di conversione della licenza. Per informazioni sulla fine disponibilità delle licenze basate su nodi, fare riferimento alla link:concept-licensing.html#end-of-availability-of-node-based-licenses["Fine della disponibilità delle licenze basate su nodi"].

Prima di procedere alla transizione, è opportuno familiarizzare con la differenza tra i due modelli di licenza. La licenza basata su nodi include capacità fissa per ogni istanza di ONTAP, che può limitare la flessibilità. Le licenze basate sulla capacità, invece, consentono di creare un pool di storage condiviso su più istanze, offrendo una maggiore flessibilità, ottimizzando l'utilizzo delle risorse e riducendo il potenziale di penalizzazione finanziaria durante la ridistribuzione dei carichi di lavoro. La ricarica basata sulla capacità si adatta perfettamente ai requisiti di storage in continua evoluzione.

Per informazioni su come eseguire questa conversione, fare riferimento alla link:task-convert-node-capacity.html["Converti le licenze basate su nodi in base alla capacità"].


NOTE: La conversione di un sistema da licenze basate sulla capacità a licenze basate su nodi non è supportata.
