---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.

Queste limitazioni sono specifiche per la gestione di Cloud Volumes ONTAP in BlueXP. Per visualizzare le limitazioni del software Cloud Volumes ONTAP, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Vai alle Note di rilascio di Cloud Volumes ONTAP"^]



== BlueXP non supporta la creazione di volumi FlexGroup

Sebbene Cloud Volumes ONTAP supporti i volumi FlexGroup, attualmente BlueXP non supporta la creazione di volumi FlexGroup. Se si crea un volume FlexGroup da Gestore di sistema o dall'interfaccia CLI, impostare la modalità di gestione della capacità di BlueXP su Manuale. La modalità automatica potrebbe non funzionare correttamente con i volumi FlexGroup.


NOTE: La possibilità di creare volumi FlexGroup in BlueXP è prevista per una release futura.



== BlueXP non supporta S3 con Cloud Volumes ONTAP

Sebbene Cloud Volumes ONTAP supporti S3 come opzione per lo storage scale-out in alcuni provider cloud, BlueXP non fornisce alcuna funzionalità di gestione per questa funzionalità. L'utilizzo della CLI è la procedura consigliata per configurare l'accesso al client S3 da Cloud Volumes ONTAP. Per ulteriori informazioni, fare riferimento a. http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["Guida all'alimentazione per la configurazione S3"^].

link:concept-client-protocols.html["Scopri di più sul supporto Cloud Volumes ONTAP per S3 e altri protocolli client"].



== BlueXP non supporta il disaster recovery per le VM di storage

BlueXP non fornisce alcun supporto di configurazione o orchestrazione per il disaster recovery delle macchine virtuali dello storage. È necessario utilizzare System Manager o la CLI.

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guida rapida alla preparazione del disaster recovery per SVM"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guida di SVM Disaster Recovery Express"^]

