---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: La configurazione predefinita di Cloud Volumes ONTAP consente di configurare e amministrare i sistemi, in particolare se si conosce ONTAP perché la configurazione predefinita di Cloud Volumes ONTAP è diversa da ONTAP. 
---
= Configurazione predefinita per Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La configurazione predefinita di Cloud Volumes ONTAP consente di configurare e amministrare i sistemi, in particolare se si conosce ONTAP perché la configurazione predefinita di Cloud Volumes ONTAP è diversa da ONTAP.



== Impostazione predefinita

* BlueXP crea una VM di storage per il servizio dei dati quando implementa Cloud Volumes ONTAP. Alcune configurazioni supportano macchine virtuali storage aggiuntive. link:task-managing-svms.html["Scopri di più sulla gestione delle VM di storage"].
+
A partire dalla versione BlueXP 3.9.5, il reporting dello spazio logico viene attivato sulla VM di storage iniziale. Quando lo spazio viene segnalato logicamente, ONTAP riporta lo spazio del volume in modo che tutto lo spazio fisico salvato dalle funzionalità di efficienza dello storage venga riportato come utilizzato.

* BlueXP installa automaticamente le seguenti licenze di ONTAP Feature su Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** Gestione delle chiavi di crittografia multi-tenant (MTEKM), a partire da Cloud Volumes ONTAP 9.12.1 GA
** Crittografia dei volumi di NetApp (solo per sistemi BYOL (Bring Your Own License) o pay-as-you-go (PAYGO) registrati)
** NFS




ifdef::aws[]

endif::aws[]

ifdef::azure[]

endif::azure[]

* SnapMirror
* SnapRestore
* SnapVault
+
** Per impostazione predefinita, vengono create diverse interfacce di rete:


* Una LIF di gestione del cluster
* Un LIF intercluster


ifdef::azure[]

* Una LIF di gestione SVM sui sistemi ha in Azure


endif::azure[]

ifdef::gcp[]

* Una LIF di gestione SVM sui sistemi ha in Google Cloud


endif::gcp[]

ifdef::aws[]

* LIF di gestione SVM su sistemi a nodo singolo in AWS


endif::aws[]

* Una LIF di gestione dei nodi


ifdef::gcp[]

+ in Google Cloud, questa LIF è combinata con la LIF intercluster.

endif::gcp[]

* Una LIF di dati iSCSI
* Una LIF di dati CIFS e NFS
+

NOTE: Il failover LIF è disattivato per impostazione predefinita per Cloud Volumes ONTAP a causa dei requisiti del cloud provider. La migrazione di una LIF a una porta diversa interrompe la mappatura esterna tra gli indirizzi IP e le interfacce di rete sull'istanza, rendendo la LIF inaccessibile.

+
** Cloud Volumes ONTAP invia i backup della configurazione al connettore utilizzando HTTP.
+
I backup sono accessibili da http://ipaddress/occm/offboxconfig/ dove _ipaddress_ è l'indirizzo IP dell'host del connettore.

+
È possibile utilizzare i backup per riconfigurare il sistema Cloud Volumes ONTAP. Per ulteriori informazioni sui backup di configurazione, fare riferimento a https://docs.netapp.com/us-en/ontap/system-admin/config-backup-file-concept.html["Documentazione ONTAP"].

** BlueXP  imposta alcuni attributi di volume in modo diverso rispetto ad altri strumenti di gestione (ad esempio, ONTAP System Manager o la CLI di ONTAP).
+
Nella tabella seguente sono elencati gli attributi del volume impostati da BlueXP in modo diverso dai valori predefiniti:

+
[cols="15,85"]
|===
| Attributo | Valore impostato da BlueXP 


| Modalità di dimensionamento automatico | crescere 


| Dimensionamento automatico massimo  a| 
1,000%


NOTE: L'organizzazione o l'amministratore dell'account BlueXP  può modificare questo valore dalla pagina Impostazioni.



| Stile di sicurezza | NTFS per CIFS Volumes UNIX per NFS Volumes 


| Stile garanzia di spazio | nessuno 


| Autorizzazioni UNIX (solo NFS) | 777 
|===
+
Per informazioni su questi attributi, fare riferimento a link:https://docs.netapp.com/us-en/ontap-cli-9121/volume-create.html["ONTAP _volume create_ man page"].







== Dischi interni per i dati di sistema

Oltre allo storage per i dati degli utenti, BlueXP acquista anche lo storage cloud per i dati di sistema.

ifdef::aws[]



=== AWS

* Tre dischi per nodo per i dati di boot, root e core:
+
** 47 disco GiB io1 per i dati di avvio
** Disco gp3 da 140 GiB per i dati root
** Disco gp2 da 540 GiB per i dati principali


* Per coppie ha:
+
** Due volumi EBS da ST1 gb per l'istanza del mediatore, uno di circa 8 GiB come disco root e uno di 4 GiB come disco dati
** Un disco da 140 GiB GP3 in ciascun nodo per contenere una copia dei dati root dell'altro nodo
+

NOTE: In alcune zone, il tipo di disco EBS disponibile può essere solo GP2.



* Un'istantanea EBS per ogni disco di boot e disco root
+

NOTE: Le snapshot vengono create automaticamente al riavvio.

* Quando si attiva la crittografia dei dati in AWS utilizzando il servizio di gestione delle chiavi (KMS), vengono crittografati anche i dischi di avvio e i dischi root per Cloud Volumes ONTAP. Questo include il disco di boot per l'istanza del mediatore in una coppia ha. I dischi vengono crittografati utilizzando la CMK selezionata quando si crea l'ambiente di lavoro.



TIP: In AWS, la NVRAM si trova sul disco di avvio.

endif::aws[]

ifdef::azure[]



=== Azure (nodo singolo)

* Tre dischi SSD Premium:
+
** Un disco da 10 GiB per i dati di avvio
** Un disco da 140 GiB per i dati root
** Un disco da 512 GiB per NVRAM
+
Se la macchina virtuale scelta per Cloud Volumes ONTAP supporta gli SSD Ultra, il sistema utilizza un SSD Ultra da 32 GB per la NVRAM, anziché un SSD Premium.



* Un disco HDD standard da 1024 GiB per il risparmio dei core
* Uno snapshot Azure per ogni disco di boot e disco root
* Per impostazione predefinita, ogni disco in Azure viene crittografato a riposo.
+
Se la macchina virtuale scelta per Cloud Volumes ONTAP supporta il disco SSD Premium v2 gestito come dischi dati, il sistema utilizza un disco gestito v2 GiB Premium SSD da 32 GB per NVRAM e un altro disco come disco principale.





=== Azure (coppia ha)

.COPPIE HA con il blob di pagina
* Due dischi SSD Premium da 10 GiB per il volume di boot (uno per nodo)
* Due blob di pagina 140 GiB Premium Storage per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il risparmio di core (uno per nodo)
* Due dischi SSD Premium da 512 GiB per NVRAM (uno per nodo)
* Uno snapshot Azure per ogni disco di boot e disco root
+

NOTE: Le snapshot vengono create automaticamente al riavvio.

* Per impostazione predefinita, ogni disco in Azure viene crittografato a riposo.


.Coppie HA con dischi gestiti condivisi in più zone di disponibilità
* Due dischi SSD Premium da 10 GiB per il volume di boot (uno per nodo)
* Due dischi SSD GiB Premium da 512 GB per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il risparmio di core (uno per nodo)
* Due dischi SSD Premium da 512 GiB per NVRAM (uno per nodo)
* Uno snapshot Azure per ogni disco di boot e disco root
+

NOTE: Le snapshot vengono create automaticamente al riavvio.

* Per impostazione predefinita, ogni disco in Azure viene crittografato a riposo.


.Coppie HA con dischi gestiti condivisi in singole zone di disponibilità
* Due dischi SSD Premium da 10 GiB per il volume di boot (uno per nodo)
* Due dischi SSD Shared Managed Premium da 512 GB per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il risparmio di core (uno per nodo)
* Due dischi gestiti SSD Premium da 512 GiB per NVRAM (uno per nodo)


Se la macchina virtuale supporta dischi SSD Premium v2 gestiti come dischi dati, utilizza 32 dischi SSD Premium v2 GiB per NVRAM e 512 dischi gestiti condivisi SSD Premium v2 GiB per il volume root.

Puoi implementare coppie ha in una singola zona di disponibilità e utilizzare dischi gestiti SSD Premium da v2 TB quando sono soddisfatte le seguenti condizioni:

* La versione di Cloud Volumes ONTAP è la 9.15.1 o successiva.
* La regione e la zona selezionate supportano dischi gestiti SSD Premium da v2 GB. Per informazioni sulle regioni supportate, fare riferimento a  https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Sito Web di Microsoft Azure: Prodotti disponibili per area geografica"^].
* L'abbonamento è registrato per Microsoft link:task-saz-feature.html["Funzione Microsoft.Compute/VMOrchestratorZonalMultiFD"].


endif::azure[]

ifdef::gcp[]



=== Google Cloud (nodo singolo)

* Un disco persistente SSD da 10 GiB per i dati di avvio
* Un disco persistente SSD da 64 GiB per i dati root
* Un disco persistente SSD da 500 GiB per NVRAM
* Un disco persistente standard da 315 GiB per il risparmio dei core
* Snapshot per i dati di boot e root
+

NOTE: Le snapshot vengono create automaticamente al riavvio.

* I dischi di boot e root sono crittografati per impostazione predefinita.




=== Google Cloud (coppia ha)

* Due dischi persistenti SSD da 10 GiB per i dati di avvio
* Quattro dischi persistenti SSD da 64 GiB per i dati root
* Due dischi persistenti SSD da 500 GiB per NVRAM
* Due dischi persistenti standard da 315 GiB per il risparmio dei core
* Un disco persistente standard da 10 GiB per i dati del mediatore
* Un disco persistente standard da 10 GiB per i dati di avvio del mediatore
* Snapshot per i dati di boot e root
+

NOTE: Le snapshot vengono create automaticamente al riavvio.

* I dischi di boot e root sono crittografati per impostazione predefinita.


endif::gcp[]



=== Dove risiedono i dischi

BlueXP definisce lo storage come segue:

* I dati di avvio risiedono su un disco collegato all'istanza o alla macchina virtuale.
+
Questo disco, che contiene l'immagine di avvio, non è disponibile per Cloud Volumes ONTAP.

* I dati root, che contengono la configurazione del sistema e i log, risiedono in aggr0.
* Il volume root della macchina virtuale di storage (SVM) risiede in aggr1.
* I volumi di dati risiedono anche in aggr1.

