---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Cloud Volumes ONTAP utilizza un collegamento privato Azure per le connessioni agli account di storage associati. Se necessario, è possibile disattivare Azure Private Links e utilizzare gli endpoint del servizio. 
---
= Configurare la creazione di gruppi di posizionamento per le coppie ha Cloud Volumes ONTAP in AWS single AZS
:allow-uri-read: 


[role="lead"]
In caso di errore della creazione del gruppo di posizionamento, le implementazioni ad alta disponibilità (ha) di Cloud Volumes ONTAP in AWS Single Availability zone (AZ) possono eseguire il failback. Anche la creazione del gruppo di posizionamento non riesce e la distribuzione torna indietro se il nodo Cloud Volumes ONTAP e l'istanza del mediatore non sono disponibili. Per evitare questo problema, è possibile modificare la configurazione per consentire il completamento della distribuzione anche se la creazione del gruppo di posizionamento non riesce.

Quando si ignora il processo di rollback, il processo di distribuzione di Cloud Volumes ONTAP viene completato correttamente e viene notificato che la creazione del gruppo di posizionamento è incompleta.

.Fasi
. Utilizzare SSH per connettersi all'host del connettore e accedere.
. Passare a `/opt/application/netapp/cloudmanager/docker_occm/data`.
. Modificare `app.conf` cambiando il valore del `rollback-on-placement-group-failure` parametro in `false`. Il valore predefinito di questo parametro è `true`.
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
. Salvare il file e disconnettersi dal connettore. Non è necessario riavviare il connettore.

