---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: Utilizza il servizio di gestione delle chiavi di Google per il servizio di gestione delle chiavi di terze parti. 
---
= Gestire le chiavi di crittografia Cloud Volumes ONTAP con il servizio KMS di Google Cloud
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puoi utilizzare link:https://cloud.google.com/kms/docs["Servizio di gestione delle chiavi di Google Cloud Platform (Cloud KMS)"^] per proteggere le chiavi di crittografia Cloud Volumes ONTAP in un'applicazione implementata dalla piattaforma cloud Google.

La gestione delle chiavi con Cloud KMS può essere abilitata con l'interfaccia a riga di comando di ONTAP o l'API REST di ONTAP.

Quando si utilizza Cloud KMS, tenere presente che per impostazione predefinita viene utilizzata la LIF di un SVM di dati per comunicare con l'endpoint di gestione delle chiavi del cloud. Una rete di gestione dei nodi viene utilizzata per comunicare con i servizi di autenticazione del provider cloud (oauth2.googleapis.com). Se la rete del cluster non è configurata correttamente, il cluster non utilizzerà correttamente il servizio di gestione delle chiavi.

.Prima di iniziare
* Il tuo sistema dovrebbe eseguire Cloud Volumes ONTAP 9.10.1 o versione successiva
* È necessario utilizzare una SVM dati. Cloud KMS può essere configurato solo su una SVM dati.
* Devi essere un amministratore del cluster o di SVM
* La licenza Volume Encryption (VE) deve essere installata sull'SVM
* A partire da Cloud Volumes ONTAP 9.12.1 GA, è necessario installare anche la licenza MTEKM (Multi-tenant Encryption Key Management)
* È richiesto un abbonamento attivo a Google Cloud Platform




== Configurazione

.Google Cloud
. Nel tuo ambiente Google Cloud, link:https://cloud.google.com/kms/docs/creating-keys["Creare un anello e una chiave GCP simmetrici"^].
. Assegna un ruolo personalizzato alla chiave Cloud KMS e all'account del servizio Cloud Volumes ONTAP.
+
.. Crea il ruolo personalizzato:
+
[listing]
----
gcloud iam roles create kmsCustomRole
    --project=<project_id>
    --title=<kms_custom_role_name>
    --description=<custom_role_description>
    --permissions=cloudkms.cryptoKeyVersions.get,cloudkms.cryptoKeyVersions.list,cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get
    --stage=GA
----
.. Assegna il ruolo personalizzato che hai creato: 
`gcloud kms keys add-iam-policy-binding _key_name_ --keyring _key_ring_name_ --location _key_location_ --member serviceAccount:_service_account_Name_ --role projects/_customer_project_id_/roles/kmsCustomRole`
+

NOTE: Se utilizzi Cloud Volumes ONTAP 9.13.0 o versioni successive, non è necessario creare un ruolo personalizzato. Puoi assegnare il ruolo predefinito [`cloudkms.cryptoKeyEncrypterDecrypter` ^] ruolo.



. Scarica la chiave JSON dell'account di servizio:
`gcloud iam service-accounts keys create key-file --iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com`


.Cloud Volumes ONTAP
. Connettersi alla LIF di gestione del cluster con il client SSH preferito.
. Passare al livello di privilegio avanzato:
`set -privilege advanced`
. Creare un DNS per i dati SVM.
`dns create -domains c._<project>_.internal -name-servers _server_address_ -vserver _SVM_name_`
. Crea voce CMEK:
`security key-manager external gcp enable -vserver _SVM_name_ -project-id _project_ -key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_`
. Quando richiesto, inserire la chiave JSON dell'account di servizio dal proprio account GCP.
. Confermare che il processo di abilitazione è riuscito:
`security key-manager external gcp check -vserver _svm_name_`
. FACOLTATIVO: Creare un volume per verificare la crittografia `vol create _volume_name_ -aggregate _aggregate_ -vserver _vserver_name_ -size 10G`




== Risolvere i problemi

Se è necessario risolvere il problema, è possibile eseguire il tail dei log REST API raw nei due passaggi precedenti:

. `set d`
. `systemshell -node _node_ -command tail -f /mroot/etc/log/mlog/kmip2_client.log`

