---
sidebar: sidebar 
permalink: task-managing-svms-gcp.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver 
summary: Una VM di storage è una macchina virtuale in esecuzione in ONTAP che fornisce servizi di storage e dati ai client. Questo potrebbe essere conosciuto come SVM o vserver. Cloud Volumes ONTAP è configurato con una VM di storage per impostazione predefinita, ma alcune configurazioni supportano altre VM di storage. 
---
= Gestisci le macchine virtuali dello storage di data-service per Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una VM di storage è una macchina virtuale in esecuzione in ONTAP che fornisce servizi di storage e dati ai client. Potresti sapere che si tratta di un _SVM_ o di un _vserver_. Cloud Volumes ONTAP è configurato con una VM di storage per impostazione predefinita, ma alcune configurazioni supportano altre VM di storage.

Per creare e gestire macchine virtuali storage aggiuntive di distribuzione di dati in Google Cloud, è necessario utilizzare le API BlueXP . Ciò è dovuto al fatto che le API automatizzano il processo di creazione delle macchine virtuali storage e di configurazione delle interfacce di rete richieste. Nel creare le macchine virtuali storage, BlueXP  configura i servizi LIF richiesti, così come una LIF iSCSI necessaria per le comunicazioni SMB/CIFS in uscita dalla macchina virtuale storage.



== Numero di VM storage supportate

A partire da Cloud Volumes ONTAP 9,11.1, in base alla licenza in uso, sono supportate più macchine virtuali storage con configurazioni specifiche. Fare riferimento a https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Note di rilascio di Cloud Volumes ONTAP"^] per verificare il numero supportato di macchine virtuali storage per la propria versione di Cloud Volumes ONTAP.

Tutte le versioni di Cloud Volumes ONTAP precedenti alla 9.11.1 supportano una VM di storage di distribuzione dati e una VM di storage di destinazione utilizzate per il disaster recovery. È possibile attivare la VM di storage di destinazione per l'accesso ai dati in caso di interruzione della VM di storage di origine.



== Creare una VM di storage

In base alla tua configurazione e al tipo di licenza, puoi creare più macchine virtuali storage su un sistema a nodo singolo o in una configurazione ha (High Availability) utilizzando le API BlueXP .

.A proposito di questa attività
Quando crei Storage VM utilizzando le API, insieme alla configurazione delle interfacce di rete richieste, BlueXP  modifica anche le `default-data-files` policy sulle macchine virtuali per lo storage dei dati rimuovendo i seguenti servizi dalla LIF dati NAS e aggiungendoli alla LIF dati iSCSI utilizzata per le connessioni di gestione in uscita:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Prima di iniziare
Il connettore richiede autorizzazioni specifiche per la creazione di macchine virtuali storage per coppie ha Cloud Volumes ONTAP. Le autorizzazioni richieste sono incluse in https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Le policy fornite da NetApp"^].



=== Sistema a nodo singolo

Utilizza la seguente chiamata API per creare una VM storage su un sistema a nodo singolo.

`POST /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

Includere i seguenti parametri nel corpo della richiesta:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== Coppia HA

Utilizza la seguente chiamata API per creare una VM storage su una coppia ha:

`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`

Includere i seguenti parametri nel corpo della richiesta:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
}
----


== Gestire le VM di storage

Con le API di BlueXP , puoi rinominare ed eliminare le macchine virtuali storage sia in configurazioni a nodo singolo che in configurazioni ha.

.Prima di iniziare
Il connettore richiede autorizzazioni specifiche per la gestione delle macchine virtuali storage per coppie ha Cloud Volumes ONTAP. Le autorizzazioni richieste sono incluse in https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Le policy fornite da NetApp"^].



=== Rinominare una VM di storage

Per rinominare una VM di storage, è necessario fornire i nomi della VM di storage esistente e della nuova VM di storage come parametri.

.Fasi
* Utilizza la seguente chiamata API per rinominare una VM storage su un sistema a nodo singolo:
+
`PUT /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

+
Includere i seguenti parametri nel corpo della richiesta:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Utilizza la seguente chiamata API per rinominare una VM storage su una coppia ha:
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`

+
Includere i seguenti parametri nel corpo della richiesta:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Eliminare una VM di storage

In una configurazione ha o nodo singolo, puoi rimuovere una VM di storage se non ha volumi attivi.

.Fasi
* Utilizza la seguente chiamata API per eliminare una VM storage su un sistema a nodo singolo:
+
`DELETE /gcp/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* Utilizza la seguente chiamata API per eliminare una VM storage su una coppia ha:
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`


