---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP supporta la crittografia dei volumi NetApp (NVE) e la crittografia aggregata NetApp (NAE) con un gestore di chiavi esterno. NVE e NAE sono attivati per impostazione predefinita se si imposta un gestore di chiavi esterno.' 
---
= Crittografia dei volumi con le soluzioni di crittografia NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cloud Volumes ONTAP supporta la crittografia dei volumi NetApp (NVE) e la crittografia aggregata NetApp (NAE). NVE e NAE sono soluzioni software che consentono la crittografia dei volumi a riposo dei dati conforme a FIPS 140-2. link:concept-security.html["Scopri di più su queste soluzioni di crittografia"].

NVE e NAE sono supportati con un gestore di chiavi esterno.

ifdef::azure[]

endif::azure[]

ifdef::gcp[]

endif::gcp[]

I nuovi aggregati avranno NAE attivato per impostazione predefinita dopo aver configurato un gestore di chiavi esterno. I nuovi volumi che non fanno parte di un aggregato NAE avranno NVE abilitato per impostazione predefinita (ad esempio, se si dispone di aggregati già creati prima della configurazione di un gestore di chiavi esterno).

Cloud Volumes ONTAP non supporta la gestione delle chiavi integrata.

.Di cosa hai bisogno
Il sistema Cloud Volumes ONTAP deve essere registrato presso il supporto NetApp. Una licenza NetApp per la crittografia dei volumi viene installata automaticamente su ogni sistema Cloud Volumes ONTAP registrato presso il supporto NetApp.

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-adding-nss-accounts.html["Aggiunta di account NetApp Support Site a BlueXP"^]
* link:task-registering.html["Registrazione di sistemi pay-as-you-go"]



NOTE: BlueXP non installa la licenza NVE sui sistemi che risiedono nell'area geografica Cina.

.Fasi
. Esaminare l'elenco dei Key Manager supportati in http://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].
+

TIP: Cercare la soluzione *Key Manager*.

. link:task-connecting-to-otc.html["Connettersi all'interfaccia utente di Cloud Volumes ONTAP"^].
. Configurare la gestione esterna delle chiavi.
+
ifdef::aws[]

+
** AWS: https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-external-key-management-overview-concept.html["Per istruzioni, consultare la documentazione di ONTAP"^]




endif::aws[]

ifdef::azure[]

* Azure: link:task-azure-key-vault.html["Azure Key Vault (AKV)"]


endif::azure[]

ifdef::gcp[]

* Google Cloud: link:task-google-key-manager.html["Servizio di gestione delle chiavi Google Cloud"]


endif::gcp[]
