---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Implementa Cloud Volumes ONTAP dal marketplace di Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi utilizzare l'implementazione diretta del marketplace di Azure per implementare rapidamente e facilmente Cloud Volumes ONTAP. Dal marketplace di Azure, puoi implementare rapidamente Cloud Volumes ONTAP in pochi clic ed esplorarne le caratteristiche e le funzionalità principali nel tuo ambiente.

Per ulteriori informazioni su questa offerta, fare riferimento a link:concept-azure-mktplace-direct.html["Scopri le offerte Cloud Volumes ONTAP su BlueXP  e sul marketplace"].

.A proposito di questa attività
Il sistema Cloud Volumes ONTAP implementato utilizzando la distribuzione diretta del marketplace di Azure possiede queste proprietà. Si noti che le funzionalità di un'istanza standalone implementata attraverso il marketplace di Azure cambiano quando viene rilevata in BlueXP .

* La versione più recente di Cloud Volumes ONTAP (9.16.1 o successiva).
* Una licenza gratuita per Cloud Volumes ONTAP, limitata a 500 GiB di capacità con provisioning. Questa licenza non include il supporto NetApp e non ha data di scadenza.
* Due nodi configurati in modalità high Availability (ha) in una singola zona di disponibilità (AZ), con numeri di serie predefiniti. Le Storage Virtual Machine (VM di storage) vengono implementate in una link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["modalità di orchestrazione flessibile"].
* Un aggregato per l'istanza creata per impostazione predefinita.
* Un disco gestito SSD Premium v2 con capacità di provisioning di 500 GiB, un disco root e un disco dati.
* Una macchina virtuale per lo storage dei dati implementata con servizi dati NFS, CIFS, iSCSI e NVMe/TCP. Non è possibile aggiungere altre macchine virtuali per lo storage dei dati.
* Licenze installate per NFS, CIFS (SMB), iSCSI, protezione autonoma dal ransomware (ARP), SnapLock e SnapMirror.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["Efficienza dello storage sensibile alla temperatura (TSSE) ONTAP"^], crittografia del volume e gestione esterna delle chiavi attivate per impostazione predefinita.
* Queste funzioni non sono supportate:
+
** Tiering FabricPool
** Modifica del tipo di VM di storage
** Modalità di scrittura rapida




.Prima di iniziare
* Assicurati di disporre di un'iscrizione valida al marketplace Azure.
* Assicurati di soddisfare i requisiti di rete di un link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Implementazione HA in una singola AZ"] in Azure. Fare riferimento alla link:reference-networking-azure.html["Configura il networking Azure per Cloud Volumes ONTAP"].
* Per implementare Cloud Volumes ONTAP è necessario assegnare uno di questi ruoli di Azure:
+
** Il `contributor` ruolo con le autorizzazioni predefinite. Per ulteriori informazioni, fare riferimento alla https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Documentazione di Azure: Ruoli integrati di Azure"^] .
** Un ruolo RBAC personalizzato con le seguenti autorizzazioni. Per ulteriori informazioni, fare riferimento alla https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Documentazione di Azure: Ruoli personalizzati di Azure"^] .
+
[]
====
"Permissions": [ { "Actions": [ "Microsoft.AAD/register/action", "Microsoft.Resources/Subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write" Microsoft.Network/virtualNetworks/read" Microsoft.Compute/disks/write" Microsoft.Network/virtualNetworks/subnets/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action" Microsoft.Network/networkSecurityGroups/write" Microsoft.Compute/virtualMachineScaleSets/write", "resources/Microsoft.Network/virtualNetworks/write" Microsoft.Network/networkSecurityGroups/read" Microsoft.Network/virtualNetworks/subnets/read"", "resources/Microsoft.Compute/virtualMachines/write"", "resources/Microsoft.Compute/virtualMachines/extensions/write"", "resources/Microsoft.Network/networkInterfaces/write""

====
+

NOTE: Se hai registrato il provider di risorse "Microsoft.storage" al tuo abbonamento, non hai bisogno dell' `Microsoft.AAD/register/action`autorizzazione. Per ulteriori informazioni, fare riferimento alla https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Documentazione di Azure: Autorizzazioni di Azure per lo storage"^] .





.Fasi
. Nel sito Azure Marketplace, cerca i prodotti NetApp.
. Selezionare *NetApp Cloud Volumes ONTAP Direct*.
. Fare clic su *Crea* per avviare la distribuzione guidata.
. Selezionare un piano. L'elenco *piano* visualizza in genere le ultime versioni di Cloud Volumes ONTAP.
. Nella scheda *informazioni di base*, fornire i seguenti dettagli:
+
** *Abbonamento*: Selezionare un abbonamento. La distribuzione sarà collegata al numero di abbonamento.
** *Gruppo di risorse*: Utilizzare un gruppo di risorse esistente o crearne uno nuovo. I gruppi di risorse consentono di allocare tutte le risorse, come dischi e macchine virtuali di storage, all'interno di un singolo gruppo per un sistema Cloud Volumes ONTAP.
** *Regione*: Seleziona un'area che supporta l'implementazione ha di Azure in una singola AZ. Vengono visualizzate solo le regioni disponibili nell'elenco.
** *Dimensione*: Selezionare una dimensione VM di archiviazione per il disco gestito SSD Premium v2 supportato.
** *Zona*: Selezionare una zona per la regione selezionata.
** *Admin Password*: Consente di impostare una password. Questa password amministratore viene utilizzata per accedere al sistema dopo la distribuzione.
** *Conferma password*: Immettere nuovamente la stessa password per la conferma.
+
*** Nella scheda *rete*, aggiungere una rete virtuale e una subnet oppure selezionarle dagli elenchi.
+

NOTE: Per rispettare le restrizioni di Microsoft Azure, è necessario creare una nuova subnet durante la configurazione di una nuova rete virtuale. Allo stesso modo, se si sceglie una rete esistente, è necessario selezionare una subnet esistente.

*** Per selezionare un gruppo di protezione di rete predefinito, selezionare *Sì*. Selezionare *No* per assegnare un gruppo di protezione di rete predefinito di Azure con le regole di traffico necessarie. Per ulteriori informazioni, fare riferimento a link:reference-networking-azure.html#security-group-rules["Regole del gruppo di sicurezza per Azure"].
*** Nella scheda *Avanzate* verificare se le due funzionalità di Azure necessarie per questa distribuzione sono state impostate. Fare riferimento a link:task-saz-feature.html["Abilita una funzionalità Azure per le implementazioni di Cloud Volumes ONTAP single AZ"] e link:task-azure-high-availability-mode.html["Abilita la modalità high Availability per Cloud Volumes ONTAP in Azure"].
*** È possibile definire coppie di nomi e valori per le risorse o i gruppi di risorse nella scheda *Tag*.
*** Nella scheda *Rivedi + crea*, esaminare i dettagli e avviare la distribuzione.






.Al termine
Selezionare l'icona di notifica per visualizzare l'avanzamento della distribuzione. Dopo l'implementazione di Cloud Volumes ONTAP, è possibile visualizzare l'elenco delle macchine virtuali per lo storage in cui sono riportate le operazioni.

Una volta accessibile, usa il System Manager di ONTAP o l'interfaccia a riga di comando di ONTAP per accedere alla macchina virtuale storage con le credenziali di amministratore impostate. Successivamente, è possibile creare volumi, LUN o condivisioni e iniziare a utilizzare le funzionalità di storage di Cloud Volumes ONTAP.



== Risolvere i problemi di implementazione

I sistemi Cloud Volumes ONTAP implementati direttamente attraverso il marketplace di Azure non includono il supporto di NetApp. In caso di problemi durante l'implementazione, puoi eseguire il troubleshooting e risolverli in maniera indipendente.

.Fasi
. Sul sito di Azure Marketplace, andare a *Diagnostica di avvio > Registro seriale*.
. Scaricare e analizzare i registri seriali.
. Consultare la documentazione del prodotto e gli articoli della Knowledge base (KB) per la risoluzione dei problemi.
+
** https://learn.microsoft.com/en-us/partner-center/["Documentazione del marketplace di Azure"]
** https://www.netapp.com/support-and-training/documentation/["Documentazione NetApp"]
** https://kb.netapp.com/["Articoli della KB di NetApp"]






== Scopri i sistemi implementati in BlueXP 

Puoi scoprire i sistemi Cloud Volumes ONTAP implementati utilizzando l'implementazione diretta del marketplace Azure e gestirli come ambienti di lavoro in BlueXP . BlueXP  Connector rileva i sistemi, li aggiunge come ambienti di lavoro, applica le licenze BlueXP  necessarie e sblocca tutte le funzionalità di BlueXP  per questi sistemi. La configurazione ha originale in una singola AZ con dischi gestiti PSSD v2 viene conservata e il sistema viene registrato nello stesso gruppo di risorse e abbonamento di Azure dell'implementazione originale.

.A proposito di questa attività
Scoprendo i sistemi Cloud Volumes ONTAP implementati utilizzando la distribuzione diretta del marketplace di Azure, BlueXP  Connector esegue le seguenti attività:

* Sostituisce le licenze gratuite dei sistemi rilevati come regolari basati sulla capacità link:concept-licensing.html#packages["Licenze Freemium"].
* Mantiene le funzionalità esistenti dei sistemi implementati e aggiunge le funzionalità aggiuntive di BlueXP , come ad esempio data Protection, gestione dei dati e funzionalità di sicurezza.
* Sostituisce le licenze installate sui nodi con nuove licenze ONTAP per NFS, CIFS (SMB), iSCSI, ARP, SnapLock e SnapMirror.
* Converte i numeri di serie dei nodi generici in numeri di serie univoci.
* Assegna nuovi tag di sistema sulle risorse in base alle necessità.
* Converte gli indirizzi IP dinamici dell'istanza in indirizzi IP statici.
* Consente di abilitare le funzionalità dello storagelink:task-tiering.html["Tiering FabricPool"] , , link:task-verify-autosupport.html["AutoSupport"]e link:concept-worm.html["write-once-read-many"] (WORM) sui sistemi distribuiti. È possibile attivare queste funzioni dalla console BlueXP  quando necessario.
* Registra le istanze negli account NSS utilizzati per rilevarle.
* Abilita le funzionalità di gestione della capacità in link:concept-storage-management.html#capacity-management["modalità automatica e manuale"] per i sistemi rilevati.


.Prima di iniziare
Assicurati che l'implementazione sia completa sul marketplace di Azure. BlueXP  Connector è in grado di rilevare i sistemi solo quando l'implementazione è completa e disponibile per il rilevamento.

.Fasi
In BlueXP , seguire la procedura standard per il rilevamento dei sistemi esistenti. Fare riferimento alla link:task-adding-systems.html["Aggiunta di un sistema Cloud Volumes ONTAP esistente a BlueXP "].

.Al termine
Al termine del rilevamento, è possibile visualizzare i sistemi elencati come ambienti di lavoro in BlueXP . È possibile eseguire diverse attività di gestione, quali link:task-manage-aggregates.html["espansione dell'aggregato"], link:task-create-volumes.html["aggiunta di volumi"], link:task-managing-svms-azure.html["Provisioning di VM di storage aggiuntive"]e link:task-change-azure-vm.html["modifica dei tipi di istanza"].

.Link correlati
Fare riferimento alla documentazione di ONTAP per ulteriori informazioni sulla creazione dello storage:

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Creare volumi per NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Creare LUN per iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Crea condivisioni per CIFS"^]

