---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, bluexp license conversion for node based 
summary: 'Dopo la fine della disponibilità (EOA) delle licenze basate su nodi, è necessario passare alla licenza basata sulla capacità utilizzando il tool di conversione delle licenze BlueXP .' 
---
= Convertire una licenza basata su nodi Cloud Volumes ONTAP in una licenza basata sulla capacità
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo la fine della disponibilità (EOA) delle licenze basate su nodi, è necessario passare alla licenza basata sulla capacità utilizzando il tool di conversione delle licenze BlueXP .

Per gli impegni annuali o a lungo termine, NetApp consiglia di contattare il rappresentante NetApp prima della data di fine disponibilità (11 novembre, 2024) o della data di scadenza della licenza, per verificare che siano in vigore i prerequisiti per la transizione. Se non disponi di un contratto a lungo termine per un nodo Cloud Volumes ONTAP ed esegui il sistema su un abbonamento PAY-as-you-go (PAYGO) on-demand, è importante pianificare la conversione prima della fine del supporto (EOS) il 31 dicembre, 2024. In entrambi i casi, è necessario assicurarsi che il sistema soddisfi i requisiti prima di utilizzare lo strumento di conversione delle licenze BlueXP  per una transizione senza problemi.

Per informazioni sulla fine disponibilità e l'EOS, fare riferimento alla link:concept-licensing.html#end-of-availability-of-node-based-licenses["Fine della disponibilità delle licenze basate su nodi"].

.A proposito di questa attività
* Quando utilizzi il tool di conversione delle licenze, il passaggio dal modello di licenza basato su nodi a quello basato sulla capacità viene eseguito sul posto e online, in modo da eliminare la necessità di migrazione dei dati o provisioning di risorse cloud aggiuntive.
* Si tratta di un'operazione senza interruzioni e non si verificano interruzioni del servizio o downtime dell'applicazione.
* I dati dell'account e dell'applicazione nel sistema Cloud Volumes ONTAP rimangono intatti.
* Le risorse cloud sottostanti rimangono invariate dopo la conversione.
* Il tool di conversione delle licenze supporta tutti i tipi di implementazione, come nodo singolo, alta disponibilità (ha) in una singola zona di disponibilità (AZ), ha in più AZ, Bring Your Own License (BYOL) e PAYGO.
* Lo strumento supporta tutte le licenze basate su nodi come origine e tutte le licenze basate su capacità come destinazione. Ad esempio, se si dispone di una licenza basata su nodi PAYGO Standard, è possibile convertirla in qualsiasi licenza basata su capacità acquistata tramite il marketplace. NetApp ha limitato l'acquisto, l'estensione e il rinnovo delle licenze BYOL. Per ulteriori informazioni, consultare  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilità limitata delle licenze BYOL per Cloud Volumes ONTAP"^] .
* La conversione è supportata per tutti i cloud provider, AWS, Azure e Google Cloud.
* Dopo la conversione, il numero di serie della licenza basata su nodo verrà sostituito da un formato basato sulla capacità. Questa operazione viene eseguita come parte della conversione e si riflette sull'account del sito di supporto NetApp (NSS).
* Durante il passaggio al modello basato sulla capacità, i dati continuano a essere conservati nella stessa posizione della licenza basata su nodi. Questo approccio garantisce l'assenza di interruzioni nel posizionamento dei dati e il rispetto dei principi di sovranità dei dati durante la transizione.


.Prima di iniziare
* È necessario disporre di un account NSS con accesso al cliente o all'amministratore.
* L'account NSS deve essere registrato con le credenziali utente BlueXP .
* L'ambiente di lavoro deve essere collegato all'account NSS con accesso al cliente o all'amministratore.
* Devi disporre di una licenza valida basata sulla capacità, che sia una licenza BYOL o un'iscrizione al marketplace.
* Nell'account BlueXP  dovrebbe essere disponibile una licenza basata sulla capacità. Questa licenza può essere un'iscrizione al marketplace o un pacchetto BYOL/offerta privata nel portafoglio digitale di BlueXP .
* Prima di selezionare un pacchetto di destinazione, comprendere i seguenti criteri:
+
** Se l'account dispone di una licenza BYOL basata sulla capacità, il pacchetto di destinazione selezionato deve allinearsi alle licenze BYOL basate sulla capacità dell'account:
+
*** Quando `Professional` viene selezionato come pacchetto di destinazione, l'account deve disporre di una licenza BYOL con un pacchetto Professional:
*** Quando `Essentials` viene selezionato come pacchetto di destinazione, l'account deve disporre di una licenza BYOL con il pacchetto Essentials.


** Se il pacchetto di destinazione non si allinea con la disponibilità della licenza BYOL dell'account, significa che la licenza basata sulla capacità potrebbe non includere il pacchetto selezionato. In questo caso, ti verrà addebitato il costo tramite l'abbonamento al mercato.
** Se non esiste una licenza BYOL basata sulla capacità ma solo un'iscrizione al marketplace, devi assicurarti che il pacchetto selezionato sia incluso nell'iscrizione al marketplace basato sulla capacità.
** Se non c'è capacità sufficiente nella tua licenza esistente basata sulla capacità e se hai un'iscrizione al marketplace per addebitare l'utilizzo di capacità aggiuntiva, ti verrà addebitato la capacità aggiuntiva tramite l'iscrizione al marketplace.
** Se la tua licenza esistente basata sulla capacità non dispone di capacità sufficiente e non disponi di un abbonamento al marketplace per addebitare l'utilizzo della capacità aggiuntiva, la conversione non può avvenire. Devi aggiungere un'iscrizione al marketplace per addebitare la capacità aggiuntiva o estendere la capacità disponibile alla tua licenza attuale.
** Se il pacchetto di destinazione non si allinea con la disponibilità della licenza BYOL dell'account e anche se non c'è capacità sufficiente nella tua licenza esistente basata sulla capacità, ti verrà addebitato il costo dell'abbonamento al marketplace.





NOTE: Se uno di questi requisiti non è soddisfatto, la conversione della licenza non avviene. In casi specifici, la licenza potrebbe essere convertita, ma non può essere utilizzata. Fare clic sull'icona delle informazioni per identificare i problemi e intraprendere azioni correttive.

.Fasi
. Nella pagina Canvas, fare doppio clic sul nome dell'ambiente di lavoro per il quale si desidera modificare il tipo di licenza.
. Nella scheda Panoramica, fare clic sul pannello funzioni.
. Controllare l'icona a forma di matita accanto a *metodo di ricarica*. Se il metodo di ricarica per il sistema è `Node Based`, è possibile convertirlo in ricarica per capacità.
+

TIP: L'icona è disattivata se il sistema Cloud Volumes ONTAP è già caricato in base alla capacità o se uno dei requisiti non è soddisfatto.

. Nella schermata *Converti licenze basate su nodo in basate sulla capacità*, verificare il nome dell'ambiente di lavoro e i dettagli della licenza di origine.
. Selezionare il pacchetto di destinazione per la conversione della licenza esistente:
+
** Indispensabili. Il valore predefinito è `Essentials`.
** Professionale


. Se disponi di una licenza BYOL, puoi selezionare la casella di controllo per eliminare la licenza basata su nodo dalla post conversione del Digital Wallet di BlueXP . Se la conversione non è completa, anche selezionando questa casella di controllo, la licenza non verrà eliminata dal portafoglio digitale. Se hai un abbonamento al mercato, questa opzione non è disponibile.
. Selezionare la casella di controllo per confermare di aver compreso le implicazioni della modifica, quindi fare clic su *Procedi*.


.Al termine
Visualizzare il nuovo numero di serie della licenza e verificare le modifiche apportate al portafoglio digitale di BlueXP .



== Prezzi in diversi iperscalari

Per i dettagli sui prezzi, vai a https://bluexp.netapp.com/pricing/["Sito Web di NetApp BlueXP"^] .

Per informazioni sulle offerte private in specifici iperscalari, scrivere a:

* AWS - awspo@netapp.com
* Azzurro - azurepo@netapp.com
* Google Cloud - gcppo@netapp.com

